install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.60.1/hugo_0.60.1_Linux-64bit.deb
  - sudo dpkg -i hugo_0.60.1_Linux-64bit.deb
script:
  - hugo
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $github_token
    keep_history: true
    local_dir: public
    on:
      branch: master
